### ISSUE TITLE
secp256k1_ec_pubkey_create?

### ISSUE THREAD

**Issue by Eric898989** [hhanh00/secp256k1-cl#2]
Why didn't you implement batch secp256k1_ec_pubkey_create operations with openCl?

**Comment by hhanh00** [comment]
Well, unless you are creating a zillion keys there wouldn't be much gain.

**Comment by Eric898989** [comment]
Would it be faster than https://github.com/ryancdotorg/brainflayer thanks to OpenCl?

**Comment by rvorias** [comment]
Hi, sorry to bump this old thread, but I'm interested in creating a zillion keys. Any tips for where to start?
